name: Jekyll Themes
url: http://jekyllthemes.oonlab.com
description: Jekyllthemes preview

permalink: /themes/:title/

pygments: true
paginate: 10

markdown: rdiscount
rdiscount:
    extensions: ['smart']
    
sass:
  sass_dir: _sass
  style: compressed

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
