name: Jekyll Themes
url: http://jekyllthemes.oonlab.com
description: Jekyllthemes preview

permalink: /themes/:title/

pygments: true
paginate: 10

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
